[
  {
    "poster": {
      "poster_name": "Shamim Siddiquee",
      "poster_handle": "shamim"
    },
    "time_stamp": "2021-05-01 10:47:35",
    "text": "```const companies=[1,2,3,4,5,....1000];\n\n    for (let company of companies) {\n       let{data} =await axios.get(\"HubSpot-API-url\"+company);\n    }```\nabove code run perfectly but after a while showing the error \"Request failed with status code 429\",  Is there any way to know the requested API completed his job, now request for the next one.",
    "reply_count": 3,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2021-05-02 09:38:24"
      },
      {
        "time_stamp": "2021-05-02 09:39:02"
      },
      {
        "time_stamp": "2021-05-02 09:39:56"
      }
    ]
  }
]