[
  {
    "poster": {
      "poster_name": "Vishal Mandora",
      "poster_handle": "vishal"
    },
    "time_stamp": "2023-10-29 22:26:42",
    "edited": {
      "time_stamp": "2023-10-30 01:21:11"
    },
    "text": "Hello everyone,\n\nI’ve a problem with workflow sometimes. & it happens randomly.\n\nhere’s the error log for the same. Can someone please explain what’s the reason behind it?\n```2023-10-29T05:00:16.423Z\tERROR\tUnhandled Promise Rejection \t{\"errorType\":\"Runtime.UnhandledPromiseRejection\",\"errorMessage\":\"Error: Client network socket disconnected before secure TLS connection was established\",\"reason\":{\"message\":\"Client network socket disconnected before secure TLS connection was established\",\"name\":\"Error\",\"stack\":\"Error: Client network socket disconnected before secure TLS connection was established\\n    at connResetException (node:internal/errors:705:14)\\n    at TLSSocket.onConnectEnd (node:_tls_wrap:1594:19)\\n    at TLSSocket.emit (node:events:525:35)\\n    at endReadableNT (node:internal/streams/readable:1358:12)\\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\",\"config\":{\"url\":\"<https://XXXX.XXX/api/HubSpot/daily-company-sync>\",\"method\":\"post\",\"data\":\"{\\\"object\\\":{\\\"objectId\\\":9051333891,\\\"objectType\\\":\\\"COMPANY\\\"},\\\"api_token\\\":\\\"XXXXXXXXXXXXX\\\"}\",\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/json;charset=utf-8\",\"User-Agent\":\"axios/0.20.0\",\"Content-Length\":95},\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1},\"code\":\"ECONNRESET\"},\"promise\":{},\"stack\":[\"Runtime.UnhandledPromiseRejection: Error: Client network socket disconnected before secure TLS connection was established\",\"    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)\",\"    at process.emit (node:events:513:28)\",\"    at emit (node:internal/process/promises:140:20)\",\"    at processPromiseRejections (node:internal/process/promises:274:27)\",\"    at processTicksAndRejections (node:internal/process/task_queues:97:32)\"]}\nUnknown application error occurred\nRuntime.Unknown\n\nMemory: 111/128 MB\nRuntime: 1220.95 ms```",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2023-10-30 01:19:50"
      }
    ]
  }
]