[
  {
    "poster": {
      "poster_name": "Amrou Bellalouna",
      "poster_handle": "amrbellalouna"
    },
    "time_stamp": "2021-08-12 02:04:42",
    "text": "What's even weirder now is, I got an oauth token and when I query a specific invoice, I get a 404 ...\nEven though I see it !"
  },
  {
    "poster": {
      "poster_name": "Amrou Bellalouna",
      "poster_handle": "amrbellalouna"
    },
    "time_stamp": "2021-08-12 02:12:36",
    "text": "good"
  },
  {
    "poster": {
      "poster_name": "Jaydeep",
      "poster_handle": "jaydeep"
    },
    "time_stamp": "2021-08-12 02:47:01",
    "text": "why i am not access marketing email api\ni already add content scope in my app i developer account",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2021-08-25 00:34:53"
      }
    ]
  },
  {
    "text": "Hi there team ^^! (not sure I should post this here, please redirect me in the right place of not)\n\nThere is an error calling the HubSpot API from the custom code, ‘The action will retry soon.‘(see pics, code below)\n\nWhen do I recieve that message? Is this an authendication problem? Am I using the api wrongly in the custom code? Is there a problem with my API key?\n\nps: I’m working here with custom code in an action as part of a workflow (see last pic) which supports only NodeJS.\n\n```const HubSpot = require('@HubSpot/api-client');\n\nexports.main = (event, callback) =&gt; {\n  const HubSpotClient = new HubSpot.Client({ apiKey: \"inserted the key myself here\" });\n\n  const dealId = \"4052177067\";\n  const toObjectType = \"Line_items\";\n  const after = undefined;\n  const limit = 500;\n\n  HubSpotClient.crm.deals.associationsApi.getAll(dealId, toObjectType, after, limit).then(results =&gt; {\n    let response = JSON.stringify(results.body, null, 2);\n    callback({outputFields: {lineItem_ID_ComOps: response.results.id}});\n  });\n}```",
    "time_stamp": "2021-08-12 03:54:21",
    "reply_count": 11,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2021-08-12 07:13:43"
      },
      {
        "time_stamp": "2021-08-12 07:20:03"
      },
      {
        "time_stamp": "2021-08-12 16:19:10"
      },
      {
        "time_stamp": "2021-08-13 01:34:53"
      },
      {
        "time_stamp": "2021-08-13 13:31:25"
      },
      {
        "time_stamp": "2021-08-13 15:33:31"
      },
      {
        "time_stamp": "2021-08-16 13:30:15"
      },
      {
        "time_stamp": "2021-08-16 13:30:52"
      },
      {
        "time_stamp": "2021-08-16 14:24:00"
      },
      {
        "time_stamp": "2021-08-17 01:08:22"
      },
      {
        "time_stamp": "2021-08-17 15:31:15"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Arno Van de Weyer",
      "poster_handle": "arno.vdw"
    },
    "time_stamp": "2021-08-12 05:11:35",
    "text": "Sound like you're having a good time :joy:"
  },
  {
    "poster": {
      "poster_name": "Oleksandr Yermolenko",
      "poster_handle": "oyermolenko"
    },
    "time_stamp": "2021-08-12 05:44:14",
    "text": "Hello!\nIs it possible to submit a \"regular form\" using this API <https://legacydocs.HubSpot.com/docs/methods/forms/submit_form>  ?\nlooks like it works only for a \"non HubSpot form\"",
    "reply_count": 4,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2021-08-25 00:35:57"
      },
      {
        "time_stamp": "2021-08-25 00:36:22"
      },
      {
        "time_stamp": "2021-08-25 00:36:36"
      },
      {
        "time_stamp": "2021-08-25 00:36:57"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Amrou Bellalouna",
      "poster_handle": "amrbellalouna"
    },
    "time_stamp": "2021-08-12 06:56:08",
    "text": "I swear to you, I don't get it."
  },
  {
    "poster": {
      "poster_name": "Angus Gibbs",
      "poster_handle": "agibbs"
    },
    "time_stamp": "2021-08-12 07:13:43",
    "text": "Hey <@U02ALQ1P3V1>, did these errors ever clear up? This usually happens when your custom code is rate limited by the HubSpot API; when that happens we will automatically retry the custom code at a later time.\n\nAlso, just FYI that there’s a <#C019VT42R8X|workflows> channel that you can also use to ask custom code related questions!"
  },
  {
    "text": "Not in my understanding, they did not clear up, see pic tho, not so sure on it.\n\nThank you for the heads up, should I go and address this issue in there?",
    "time_stamp": "2021-08-12 07:20:03"
  },
  {
    "poster": {
      "poster_name": "Álvaro Castellanos López",
      "poster_handle": "alvaro747"
    },
    "time_stamp": "2021-08-12 08:30:44",
    "text": "Hi! :wave:\n\nThis Álvaro, from LeadIQ. I have the following question:\n\nWe are using the old API and we have seen that `profile-url` was deprecated, therefore we have seen that we have to build the contact URL from ourselves having `vid` and `portal-id` (hub id). Something like:\n<https://app.HubSpot.com/contacts/:hubid/contact/:vid> (ref <https://community.HubSpot.com/t5/APIs-Integrations/Property-quot-profile-url-quot-is-missing-in-the-response-to-my/m-p/472499|link>)\n\nI’ve created an account to make some tests and I’ve realized that my subdomain is `app-eu1` (<http://app-eu1.HubSpot.com|app-eu1.HubSpot.com>) so if I use <https://app.HubSpot.com/contacts/:hubid/contact/:vid> doesn’t redirect properly.\n\nIs this something known? if yes, how do you deal with it?\n\nWe would need to build the URL depending on where the user comes from (e.g. `app-ue1`, `app`, and so on)\n\nThanks",
    "reply_count": 8,
    "reply_users_count": 3,
    "replies": [
      {
        "time_stamp": "2021-08-25 00:38:01"
      },
      {
        "time_stamp": "2021-08-25 10:03:00"
      },
      {
        "time_stamp": "2021-08-26 13:02:48"
      },
      {
        "time_stamp": "2021-09-07 07:07:18"
      },
      {
        "time_stamp": "2021-09-07 07:07:34"
      },
      {
        "time_stamp": "2021-09-07 07:24:04"
      },
      {
        "time_stamp": "2021-09-07 07:54:44"
      },
      {
        "time_stamp": "2021-09-07 08:01:30"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "McCabe",
      "poster_handle": "mccabe"
    },
    "time_stamp": "2021-08-12 10:04:20",
    "edited": {
      "time_stamp": "2021-08-12 10:04:49"
    },
    "text": "When i run a PUT to update a ticket's pipeline stage, can I reference something like \"OPEN\" rather than the stage value?\ncurrently i have\n\"name\": \"hs_pipeline_stage\",\"value\": \"139102\" --  this isn't dynamic enough for multiple pipelines",
    "reply_count": 3,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2021-08-25 00:38:28"
      },
      {
        "time_stamp": "2021-08-25 00:38:44"
      },
      {
        "time_stamp": "2021-09-03 11:40:29"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Cory Park",
      "poster_handle": "cory"
    },
    "time_stamp": "2021-08-12 10:35:32",
    "text": "ooohh really?? thanks! I'll try it"
  },
  {
    "poster": {
      "poster_name": "Lily Signori",
      "poster_handle": "lily.signori"
    },
    "time_stamp": "2021-08-12 10:43:53",
    "text": "Hello! I am trying to use the HubSpot API using this method: <https://legacydocs.HubSpot.com/docs/methods/contacts/merge-contacts>.\n \nI have a CSV of \"New Contact IDs\" that need to be merged with the duplicate \"Old Contact IDs\", so I am iterating through these to bulk update by replacing the ID in the URL and the vidToMerge ID. However, I keep getting 404 and 405 errors saying the resource is not found. Here is what I have:\n\n```import csv\nimport pandas as pd\nfrom pandas import *\n \n# reading CSV file\ndata = read_csv(\"sample_import.csv\")\n# converting column data to list\nmain_contacts = data['New_Contact_ID'].tolist()\ncontacts_to_merge = data['Old_Contact_ID'].tolist()\n\nfor main_id in main_contacts:\n    endpoint = requests.get('<https://api.hubapi.com/contacts/v1/contact/merge-vids/{}/?hapikey=xxxx'.format(id)>)\n    for old_id in contacts_to_merge:\n      {\n          \"vidToMerge\": old_id\n      }```",
    "reply_count": 4,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2021-08-16 04:00:59"
      },
      {
        "time_stamp": "2021-08-16 04:02:04"
      },
      {
        "time_stamp": "2021-08-25 00:39:25"
      },
      {
        "time_stamp": "2021-08-25 00:39:41"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Ivan Homola",
      "poster_handle": "ivan479"
    },
    "time_stamp": "2021-08-12 14:30:35",
    "text": "Thanks Matthew, but we are looking for an option to implement HubSpot conversations. We found this workaround using bots but it's too complicated to setup."
  },
  {
    "poster": {
      "poster_name": "Amrou Bellalouna",
      "poster_handle": "amrbellalouna"
    },
    "time_stamp": "2021-08-12 15:36:19",
    "text": "Hey guys, I'm trying to use the extension API to get details of an invoice in quickbooks.\n\nTo make sure I didn't things wrong, here's what I did:\n1. Made an app in HubSpot with the accounting scope.\n2. Installed the app\n3. Got an OAuth token that I'll be using in the following request\nI'm using python and here's the request:\n```token = \"MY_OAUTH_TOKEN\"\nheaders = {\"Authorization\":f\"Bearer {token}\"}\n\ninvoice_id = \"INVOICE_ID\"\naccount_id = \"QUICKBOOKS_REALM_ID\"\n\nresponse = requests.get(f\"<https://api.HubSpot.com/crm/v3/extensions/accounting/invoice/{invoice_id}?accountId={account_id}>\", headers = headers)```\nWhen I do this, I get a 404 response.\nI even tried both of  the invoice's id from quickbooks and the one in HubSpot that I find in the associations.\nWhat am I doing wrong here ? (edited)",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2021-08-14 04:38:11"
      }
    ]
  },
  {
    "text": "Hi Guys could you guys let me know there is an API I can call to create a ticket in my HubSpot dashboard. I am planning to send the data from my webpage which is non-HubSpot. The picture below is the dasboard where I want the ticket t be created.",
    "time_stamp": "2021-08-12 15:49:04",
    "reply_count": 3,
    "reply_users_count": 3,
    "replies": [
      {
        "time_stamp": "2021-08-13 07:22:23"
      },
      {
        "time_stamp": "2021-08-13 07:31:41"
      },
      {
        "time_stamp": "2021-08-25 00:40:13"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Angus Gibbs",
      "poster_handle": "agibbs"
    },
    "time_stamp": "2021-08-12 16:19:10",
    "text": "Actually based on your second screenshot it looks like you’re hitting a server error. Can you try changing `toObjectType` to `LINE_ITEM` instead of `Line_items`? If that’s the problem I’ll flag this with the team to see why we aren’t validating that properly"
  }
]