[
  {
    "poster": {
      "poster_name": "Diego Vidal",
      "poster_handle": "diego.v"
    },
    "time_stamp": "2023-05-30 09:41:45",
    "edited": {
      "time_stamp": "2023-05-30 09:42:11"
    },
    "text": "Hi everybody. I need some help with the Associations API. The endpoint `/crm/v3/associations/companies/contacts/batch/read`  for batch reading responds `OBJECT_NOT_FOUND` in some cases, but the association exist. Can someone help me with this? Thanks !",
    "reply_count": 4,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2023-05-30 13:36:47"
      },
      {
        "time_stamp": "2023-05-30 13:41:00"
      },
      {
        "time_stamp": "2023-05-30 13:55:58"
      },
      {
        "time_stamp": "2023-05-31 02:05:33"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Harun Kumar Siva",
      "poster_handle": "harun"
    },
    "time_stamp": "2023-05-30 11:25:23",
    "text": "no luck at my end as well.\nlooks like people have been running into this same cryptic error for a couple of years now: <https://community.HubSpot.com/t5/HubSpot-Ideas/Improve-Import-API-error-messages-error-handling-and/idi-p/390289>"
  },
  {
    "poster": {
      "poster_name": "Valentina Varela Alzate",
      "poster_handle": "valentina.varela"
    },
    "time_stamp": "2023-05-30 12:26:29",
    "text": "How can i implemented webhooks with a python aplication, for receive contact information and save in local data base"
  },
  {
    "poster": {
      "poster_name": "Yash Kimtani",
      "poster_handle": "yash.kimtani"
    },
    "time_stamp": "2023-05-30 12:33:18",
    "text": "Hey guys, I have a card that opens a page in an IFRAME. This page contains a copy to clipboard button to copy text area. It works fine when I open this page directly (not through HubSpot) but if I open page through Iframe  action button doesn’t works.",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2023-05-30 13:05:35"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Jacob Jennings",
      "poster_handle": "jacob550"
    },
    "time_stamp": "2023-05-30 13:05:35",
    "text": "<https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard|https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard>"
  },
  {
    "poster": {
      "poster_name": "Leonardo dos Santos Canario",
      "poster_handle": "leonardo.canario"
    },
    "time_stamp": "2023-05-30 13:34:49",
    "text": "Hi guys, in HubSpot there is an API to take the API logs from a specific private app?"
  },
  {
    "poster": {
      "poster_name": "Matt Swanson",
      "poster_handle": "matt353"
    },
    "time_stamp": "2023-05-30 13:36:47",
    "text": "Hi, just wanted to say I am seeing this happening too"
  },
  {
    "poster": {
      "poster_name": "Matt Swanson",
      "poster_handle": "matt353"
    },
    "time_stamp": "2023-05-30 13:41:00",
    "text": "Try using the v4 endpoint, that seems to work for me"
  },
  {
    "poster": {
      "poster_name": "Adrian de Clickplan",
      "poster_handle": "adrian641"
    },
    "time_stamp": "2023-05-30 13:54:57",
    "text": "Hello developers! I need your help with the following issue that I am experiencing. I used Postman to make a POST request to the endpoint <https://api.hubapi.com/crm/v3/objects/contacts/search>, as the documentation suggests, and everything was correct. I performed a search for users using filters, limits, etc. However, when I apply the same approach in HubSpot using `HubSpotClient.crm.contacts.searchApi.doSearch()`, it returns an empty object, even though the JSON I am sending is exactly the same as the one I used in Postman. I appreciate the assistance in advance.\n```const HubSpot = require('@HubSpot/api-client');\n\nexports.main = (event, callback) =&gt; {\n    const HubSpotClient = new HubSpot.Client({\n        accessToken: process.env.API_HubSpot\n    });\n\n    const referrer = event.inputFields['referente'];\n    console.log(\"REFERRED ID: \" + referrer);\n\n    //2) Search for the contact using the deals referrer_id and update\n    const filter = {\n        propertyName: 'id_de_referencia',\n        operator: 'EQ',\n        value: referrer\n    }\n    const filterGroup = {\n        filters: [filter]\n    }\n    const sort = JSON.stringify({\n        propertyName: 'id_de_referencia',\n        direction: 'DESCENDING'\n    })\n    const properties = ['id_de_referencia', 'referencias_totales', 'firstname', 'lastname', 'email']\n    const limit = 100\n    const after = 0\n\n    const publicObjectSearchRequest = {\n        filterGroups: [filterGroup],\n        sorts: [sort],\n        properties,\n        limit,\n        after,\n    }\n    const doSearchApi = HubSpotClient.crm.contacts.searchApi.doSearch(publicObjectSearchRequest)\n      callback({\n    outputFields: {\n\t\tfilter:filter,\n      \tpublicObjectSearchRequest:publicObjectSearchRequest,\n      \treferrerOutput:doSearchApi,\n      \ttotal_referrals:referrer,\n    }\n  });```",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2023-05-30 14:04:53"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Matt Swanson",
      "poster_handle": "matt353"
    },
    "time_stamp": "2023-05-30 13:55:58",
    "text": "Sounds like this is because of the new association label stuff — which is only supported on the v4 endpoints"
  },
  {
    "poster": {
      "poster_name": "Adrian de Clickplan",
      "poster_handle": "adrian641"
    },
    "time_stamp": "2023-05-30 14:04:53",
    "text": "I'm adding the JSON that I'm sending for more information along with the error that the console is throwing:\n```{\n \"filterGroups\": [\n  {\n   \"filters\": [\n    {\n     \"propertyName\": \"id_de_referencia\",\n     \"operator\": \"EQ\",\n     \"value\": \"564\"\n    }\n   ]\n  }\n ],\n \"sorts\": [\n  \"{\\\"propertyName\\\":\\\"id_de_referencia\\\",\\\"direction\\\":\\\"DESCENDING\\\"}\"\n ],\n \"properties\": [\n  \"id_de_referencia\",\n  \"referencias_totales\",\n  \"firstname\",\n  \"lastname\",\n  \"email\"\n ],\n \"limit\": 100,\n \"after\": 0\n}```\n`ERROR\tCatch ERROR: TypeError: Cannot read properties of undefined (reading 'results')`"
  },
  {
    "poster": {
      "poster_name": "Arlo Gilbert",
      "poster_handle": "a"
    },
    "time_stamp": "2023-05-30 14:08:38",
    "text": "I see these scopes: `cms.knowledge_base.articles.publish` `cms.knowledge_base.articles.read` `cms.knowledge_base.articles` - Is there an endpoint for knowledgebase now?",
    "reply_count": 2,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2023-05-30 15:11:08"
      },
      {
        "time_stamp": "2024-05-22 10:05:12"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Arlo Gilbert",
      "poster_handle": "a"
    },
    "time_stamp": "2023-05-30 15:11:08",
    "text": "Answering my own question...  <https://api.hubapi.com/cms/v3/knowledge-base/articles> appears to be live however my private app credentials generate a vague error message.\n\n```{\n  \"correlationId\": \"3f3d4018-0bd6-4fa1-b47e-f99d11dd3f17\",\n  \"errorType\": \"MISSING_AUTH\",\n  \"message\": \"Not engaged, auth is missing\",\n  \"status\": \"error\"\n}```\n"
  }
]