[
  {
    "poster": {
      "poster_name": "Nathan Batdorf",
      "poster_handle": "nathan.batdorf"
    },
    "time_stamp": "2022-01-10 07:42:49",
    "text": "We have installed a plugin that syncs data from Magneto to HubSpot. It uses extensions/ecomm/v2/sync/messages. Everything has been working great so far. The client recently wanted to add a few new attributes to the CONTACT profile. I created the attribute in both Magneto 2 and HubSpot. (created_in). I verified that the new attribute is being sent over via the API call. However the property is not being updated in HubSpot. The API returns a successful response and doing a callback on the contact (sync/status/default/CONTACT) it shows that it was updated with zero errors. Has anyone run into an issue where /v2/sync/messages is not updating all of the properties?",
    "reply_count": 6,
    "reply_users_count": 3,
    "replies": [
      {
        "time_stamp": "2022-01-11 00:23:05"
      },
      {
        "time_stamp": "2022-01-11 06:49:23"
      },
      {
        "time_stamp": "2022-01-11 07:02:37"
      },
      {
        "time_stamp": "2022-01-11 19:50:39"
      },
      {
        "time_stamp": "2022-01-11 19:51:12"
      },
      {
        "time_stamp": "2022-01-11 19:53:38"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Julian L",
      "poster_handle": "julian.leidolt"
    },
    "time_stamp": "2022-01-10 11:44:34",
    "text": "Hey everyone! I am currently using the HubSpot Python HubSpot API along with Eel.\n\nEverything works fine, until I try to package the script into an .exe File using PyInstaller.\n\nI ge tthe following error in the console as soon as I try to use part of the API:\n\n```Traceback (most recent call last):\n  File \"eel\\__init__.py\", line 281, in _process_message\n  File \"C:\\Users\\User\\Documents\\New Page\\SvelteEelPython\\App\\main.py\", line 26, in py_getTicketID\n    ticket_fetched = api_client.crm.tickets.basic_api.get_by_id(id)\n  File \"HubSpot\\discovery\\crm\\tickets\\discovery.py\", line 9, in basic_api\n  File \"HubSpot\\discovery\\discovery_base.py\", line 11, in _configure_api_client\n  File \"HubSpot\\discovery\\discovery_base.py\", line 27, in _default_api_factory\n  File \"pkg_resources\\__init__.py\", line 891, in require\n  File \"pkg_resources\\__init__.py\", line 777, in resolve\npkg_resources.DistributionNotFound: The 'python-dateutil' distribution was not found and is required by HubSpot-api-client```\nUsing pip to install 'python-dateutil' did not fix this issue as it was already present in the project.\n\nHas anybody ever dealt with this issue while using the Python API?"
  },
  {
    "poster": {
      "poster_name": "Jose Nunez",
      "poster_handle": "joseenrique0595"
    },
    "time_stamp": "2022-01-10 15:03:45",
    "text": "Hi everyone! I’m working with `Delay` action on Workflows using API. Is there a way to use the “Delay until a day or time” with API? The json object shows that just the “Delay for a set amount of time” event is support it. Thanks in advance"
  },
  {
    "poster": {
      "poster_name": "Roman Kozak",
      "poster_handle": "roman.gruit"
    },
    "time_stamp": "2022-01-11 00:23:05",
    "text": "Hi <@U02FZE4AF7Z> !\nWhat plugin do you use?\n"
  }
]