[
  {
    "poster": {
      "poster_name": "Pablo Castro",
      "poster_handle": "pablo.castro"
    },
    "time_stamp": "2024-11-01 11:50:48",
    "text": "<@U07S0G1730T>, do you know what this error means?\n```{\n  \"status\":\"error\",\n  \"message\":\"Exception in external client\",\n  \"errorType\":\"SequenceError.EXTERNAL_CLIENT_EXCEPTION\"\n}```",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2024-11-01 11:51:13"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Pablo Castro",
      "poster_handle": "pablo.castro"
    },
    "time_stamp": "2024-11-01 11:51:13",
    "text": "I've searched every piece of documentation HS has and could not find what this means."
  },
  {
    "text": "Iâ€™ve hit a wall for using this API when it comes to enrolling contacts when the user that owns the sequence uses an alias instead of the primary connected account. I can enroll find using the main email account, but not the alias even though I can set the default email address in the UI when enrolling contacts to a given sequence. Is there any way around this?\n\n```{\n    \"status\": \"error\",\n    \"message\": \"Connected inbox not found or not in ENABLED state for inboxAddress\",\n    \"errorType\": \"SequenceError.CONNECTED_INBOX_NOT_FOUND\",\n    \"correlationId\": \"d98ab3f4-f4f3-40a6-93dc-8e1c789911f5\"\n}```",
    "time_stamp": "2024-11-01 17:38:48",
    "reply_count": 2,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2024-11-20 13:01:26"
      },
      {
        "time_stamp": "2024-11-20 13:21:42"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "David Panzarella",
      "poster_handle": "david818"
    },
    "time_stamp": "2024-11-01 17:40:09",
    "text": "Would like to help give some testing feedback to <@U07S0G1730T> and his team if any of them would like to chime in?"
  }
]